to_avoid = "AVOID THESE MONETISATION GAP AT ANY COST:" \
"- ANY TYPE OF SAAS or DIGITAL PORTAL OR WEB APPLICATION." \
"- DIGITAL COMMUNITY BUILDING." \
"- AFFILIATE OR AMBASSADOR PROGRAMS." \
"- SPONSORSHIPS." \
"- GENERIC PRINTABLE TEMPLATE GAP"


to_avoid_name = "AVOID THESE TYPES OF NAME AT ANY COST:" \
"- Printables Gap" \
"- Recurring Revenue Gap" \
"- Audio-Guided Prayer Retreat Gap" \
"- On-Demand Archive Gap" \
"- Affiliate & Ambassador Program Gap" \
"" \
"AVOID THESE TYPES OF NAMES OR RELATED, THESE ARE NAMES THAT CONVEY NOTHING BUT CONFUSE"


to_add = "PREFER DIGITAL REAL PRODUCTS LIKE COURSE, PDF, BOOKS etc as DIGITAL PRODUCT, EVEN IF ONLY 2-3 CAN BE IDENTIFIED. " \
"NO NEED OF ADDING 5-6 USELESS GAPS"